# To run Jekyll dev environment locally, run:
# § bundle exec jekyll serve --baseurl="" --drafts

# Configurations
title:            ⚙️ V25 Tech Training
longtitle:        ⚙️ Vineyard25 Tech Training
author:           nick@vineyard25.org
email:            nick@vineyard25.org
description:      Vineyard25 Tech Training Documentation

version:          1.0
gitbook_version:  3.2.3

url:              'https://tech.vineyard25.org'
baseurl:          '/'
rss:              RSS

#  google_analytics: "<YOUR GOOGLE ANALYTICS KEY, e.g, UA-xxxxxx-x>"

remote_theme: sighingnow/jekyll-gitbook

markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

permalink:                /:categories/:year-:month-:day-:title:output_ext

collections:
  posts:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - docs

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-target-blank

toc:
    enabled: true
    h_min: 1
    h_max: 2
